export const hajok = [
  {
    nev: "Nautivela 420",
    ar: 4615000,
    tipus: "Versenyvitorlás",
    tarolasi_hely: "Balatonfüred, Magyarország",
    feltoltesi_ido: "2025-06-01",
    kepek: "./kepek/420.png",
    gyartasi_ev: 2021,
    uzemanyag: "Nincs (vitorlás)",
    motor_le: 0,
    vitorla_felulet: 10.25,
    hossz_m: 4.2,
    utasok_szama: 2,
    szin: "Fehér-szürke",
    arboc_magassag_m: 6.26,
    vitorlak_szama: 3,
    fekvohelyek_szama: 0,
    rovid_leiras: "Nemzetközi 420 osztályú Nautivela versenyvitorlás kiváló állapotban, trapéz és spinakker felszereléssel. (ez én vagyok :D )"
  },
  {
    nev: "Elan 310",
    ar: 34900000,
    tipus: "Túravitorlás",
    tarolasi_hely: "Balatonlelle, Magyarország",
    feltoltesi_ido: "2025-05-31",
    kepek: "./kepek/Elan310.png",
    gyartasi_ev: 2015,
    uzemanyag: "Dízel",
    motor_le: 18,
    vitorla_felulet: 50.6,
    hossz_m: 9.55,
    utasok_szama: 6,
    szin: "Fehér-piros",
    arboc_magassag_m: 14.8,
    vitorlak_szama: 2,
    fekvohelyek_szama: 4,
    rovid_leiras: "Modern túravitorlás kiváló teljesítménnyel és kényelmes belső térrel."
  },
  {
    nev: "Bavaria Cruiser 34",
    ar: 42900000,
    tipus: "Családi vitorlás",
    tarolasi_hely: "Balatonfüred, Magyarország",
    feltoltesi_ido: "2025-05-20",
    kepek: "./kepek/BavariaCruiser34.png",
    gyartasi_ev: 2018,
    uzemanyag: "Dízel",
    motor_le: 30,
    vitorla_felulet: 55.2,
    hossz_m: 9.99,
    utasok_szama: 8,
    szin: "Fehér",
    arboc_magassag_m: 15.5,
    vitorlak_szama: 2,
    fekvohelyek_szama: 6,
    rovid_leiras: "Tágas családi hajó kényelmes kabinokkal és erős motorral."
  },
  {
    nev: "Jeanneau Sun Odyssey 349",
    ar: 48900000,
    tipus: "Túravitorlás",
    tarolasi_hely: "Siófok, Magyarország",
    feltoltesi_ido: "2025-05-30",
    kepek: "./kepek/JeanneauSunOdyssey349.png",
    gyartasi_ev: 2019,
    uzemanyag: "Dízel",
    motor_le: 21,
    vitorla_felulet: 59.0,
    hossz_m: 10.34,
    utasok_szama: 6,
    szin: "Fehér-szürke",
    arboc_magassag_m: 15.2,
    vitorlak_szama: 3,
    fekvohelyek_szama: 6,
    rovid_leiras: "Kiválóan kezelhető hajó modern dizájnnal és nagy belső térrel."
  },
  {
    nev: "Hanse 315",
    ar: 38900000,
    tipus: "Túravitorlás",
    tarolasi_hely: "Balatonalmádi, Magyarország",
    feltoltesi_ido: "2025-05-20",
    kepek: "./kepek/Hanse315.png",
    gyartasi_ev: 2016,
    uzemanyag: "Dízel",
    motor_le: 19,
    vitorla_felulet: 49.5,
    hossz_m: 9.62,
    utasok_szama: 5,
    szin: "Fehér-kék",
    arboc_magassag_m: 14.2,
    vitorlak_szama: 2,
    fekvohelyek_szama: 4,
    rovid_leiras: "Kompakt méretű, de jól felszerelt hajó kezdőknek és profiknak egyaránt."
  },
  {
    nev: "Dufour 360",
    ar: 55900000,
    tipus: "Luxus túravitorlás",
    tarolasi_hely: "Keszthely, Magyarország",
    feltoltesi_ido: "2025-05-19",
    kepek: "./kepek/Dufour360.png",
    gyartasi_ev: 2020,
    uzemanyag: "Dízel",
    motor_le: 30,
    vitorla_felulet: 60.0,
    hossz_m: 10.73,
    utasok_szama: 8,
    szin: "Fehér",
    arboc_magassag_m: 16.0,
    vitorlak_szama: 3,
    fekvohelyek_szama: 6,
    rovid_leiras: "Kényelmes és tágas hajó elegáns belső térrel és modern megoldásokkal."
  },
  {
    nev: "Beneteau Oceanis 30.1",
    ar: 49900000,
    tipus: "Túrahajó",
    tarolasi_hely: "Balatonboglár, Magyarország",
    feltoltesi_ido: "2025-05-17",
    kepek: "./kepek/BeneteauOceanis30.1.png",
    gyartasi_ev: 2021,
    uzemanyag: "Dízel",
    motor_le: 21,
    vitorla_felulet: 46.0,
    hossz_m: 9.53,
    utasok_szama: 6,
    szin: "Fehér-szürke",
    arboc_magassag_m: 14.9,
    vitorlak_szama: 2,
    fekvohelyek_szama: 4,
    rovid_leiras: "Modern túrahajó kompakt méretben, könnyű kezelhetőséggel."
  },
  {
    nev: "Maxus 26",
    ar: 23900000,
    tipus: "Sportvitorlás",
    tarolasi_hely: "Fonyód, Magyarország",
    feltoltesi_ido: "2025-05-21",
    kepek: "./kepek/Maxus26.png",
    gyartasi_ev: 2017,
    uzemanyag: "Benzin",
    motor_le: 15,
    vitorla_felulet: 37.5,
    hossz_m: 8.4,
    utasok_szama: 4,
    szin: "Fehér-kék",
    arboc_magassag_m: 12.5,
    vitorlak_szama: 2,
    fekvohelyek_szama: 3,
    rovid_leiras: "Könnyű és gyors hajó, ideális sportos vitorlázásra a Balatonon."
  },
  {
    nev: "Dehler 34",
    ar: 56900000,
    tipus: "Versenyvitorlás",
    tarolasi_hely: "Balatonkenese, Magyarország",
    feltoltesi_ido: "2025-05-19",
    kepek: "./kepek/Dehler34.png",
    gyartasi_ev: 2018,
    uzemanyag: "Dízel",
    motor_le: 28,
    vitorla_felulet: 65.0,
    hossz_m: 10.7,
    utasok_szama: 6,
    szin: "Fehér-vörös",
    arboc_magassag_m: 16.5,
    vitorlak_szama: 3,
    fekvohelyek_szama: 5,
    rovid_leiras: "Gyors és agilis hajó versenyekre és sportos túrákra."
  },
  {
    nev: "Elan Impression 40",
    ar: 69900000,
    tipus: "Luxus túrahajó",
    tarolasi_hely: "Balatonfüred, Magyarország",
    feltoltesi_ido: "2025-05-20",
    kepek: "./kepek/ElanImpression40.png",
    gyartasi_ev: 2022,
    uzemanyag: "Dízel",
    motor_le: 40,
    vitorla_felulet: 85.0,
    hossz_m: 11.9,
    utasok_szama: 10,
    szin: "Fehér-arany",
    arboc_magassag_m: 18.0,
    vitorlak_szama: 3,
    fekvohelyek_szama: 8,
    rovid_leiras: "Tágas, modern luxushajó nagycsaládos vagy charter célokra."
  },
];